# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 189f8c150d930ed2e61eddb6a2eb877e5e92a4fd33d5e45ccabe6121fc9e6550bdaf97838e45e744fab1691688489d3c8d4e94159da1ad757e894fd4f670fd3f

test:
  secret_key_base: 0fa8f5190c52777eeabc8fcde37785940e94f5c2b0844facd087c1301a29c9a5e6a583c6f7b52f359b8a1961b4847131628d8bdf9adb16e03d0c6c0f37c3f423

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
