require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe KontoumsatzsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Kontoumsatz. As you add validations to Kontoumsatz, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # KontoumsatzsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all kontoumsatzs as @kontoumsatzs" do
      kontoumsatz = Kontoumsatz.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:kontoumsatzs)).to eq([kontoumsatz])
    end
  end

  describe "GET #show" do
    it "assigns the requested kontoumsatz as @kontoumsatz" do
      kontoumsatz = Kontoumsatz.create! valid_attributes
      get :show, params: {id: kontoumsatz.to_param}, session: valid_session
      expect(assigns(:kontoumsatz)).to eq(kontoumsatz)
    end
  end

  describe "GET #new" do
    it "assigns a new kontoumsatz as @kontoumsatz" do
      get :new, params: {}, session: valid_session
      expect(assigns(:kontoumsatz)).to be_a_new(Kontoumsatz)
    end
  end

  describe "GET #edit" do
    it "assigns the requested kontoumsatz as @kontoumsatz" do
      kontoumsatz = Kontoumsatz.create! valid_attributes
      get :edit, params: {id: kontoumsatz.to_param}, session: valid_session
      expect(assigns(:kontoumsatz)).to eq(kontoumsatz)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Kontoumsatz" do
        expect {
          post :create, params: {kontoumsatz: valid_attributes}, session: valid_session
        }.to change(Kontoumsatz, :count).by(1)
      end

      it "assigns a newly created kontoumsatz as @kontoumsatz" do
        post :create, params: {kontoumsatz: valid_attributes}, session: valid_session
        expect(assigns(:kontoumsatz)).to be_a(Kontoumsatz)
        expect(assigns(:kontoumsatz)).to be_persisted
      end

      it "redirects to the created kontoumsatz" do
        post :create, params: {kontoumsatz: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Kontoumsatz.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved kontoumsatz as @kontoumsatz" do
        post :create, params: {kontoumsatz: invalid_attributes}, session: valid_session
        expect(assigns(:kontoumsatz)).to be_a_new(Kontoumsatz)
      end

      it "re-renders the 'new' template" do
        post :create, params: {kontoumsatz: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested kontoumsatz" do
        kontoumsatz = Kontoumsatz.create! valid_attributes
        put :update, params: {id: kontoumsatz.to_param, kontoumsatz: new_attributes}, session: valid_session
        kontoumsatz.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested kontoumsatz as @kontoumsatz" do
        kontoumsatz = Kontoumsatz.create! valid_attributes
        put :update, params: {id: kontoumsatz.to_param, kontoumsatz: valid_attributes}, session: valid_session
        expect(assigns(:kontoumsatz)).to eq(kontoumsatz)
      end

      it "redirects to the kontoumsatz" do
        kontoumsatz = Kontoumsatz.create! valid_attributes
        put :update, params: {id: kontoumsatz.to_param, kontoumsatz: valid_attributes}, session: valid_session
        expect(response).to redirect_to(kontoumsatz)
      end
    end

    context "with invalid params" do
      it "assigns the kontoumsatz as @kontoumsatz" do
        kontoumsatz = Kontoumsatz.create! valid_attributes
        put :update, params: {id: kontoumsatz.to_param, kontoumsatz: invalid_attributes}, session: valid_session
        expect(assigns(:kontoumsatz)).to eq(kontoumsatz)
      end

      it "re-renders the 'edit' template" do
        kontoumsatz = Kontoumsatz.create! valid_attributes
        put :update, params: {id: kontoumsatz.to_param, kontoumsatz: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested kontoumsatz" do
      kontoumsatz = Kontoumsatz.create! valid_attributes
      expect {
        delete :destroy, params: {id: kontoumsatz.to_param}, session: valid_session
      }.to change(Kontoumsatz, :count).by(-1)
    end

    it "redirects to the kontoumsatzs list" do
      kontoumsatz = Kontoumsatz.create! valid_attributes
      delete :destroy, params: {id: kontoumsatz.to_param}, session: valid_session
      expect(response).to redirect_to(kontoumsatzs_url)
    end
  end

end
